#!/bin/bash
function _rename
{
	prefix="$1"
	forreal="$2"
	while read file; do
		suffix="$(echo ${file##*.} | tr [:upper:] [:lower:])"
		newfile="$(printf "$fmt" "$prefix" $index "$suffix")"
		echo "Moving $file -> $newfile"
		if test "$forreal" = "y"; then
			mv "$file" "$newfile"
		fi
		index=$(($index+1))
	done
}

if test $# -lt 2; then
	echo "Usage: $0 prefix folder [real]" >&2
	exit 1
fi

prefix="$1"
if test -d "$2"; then
	cd "$2"
else
	echo "$2 not found" >&2
	exit 1
fi

if test "$3" = "real"; then
	forreal="y"
else
	forreal=""
fi

set -- $(ls | grep -v "~$" | wc)
files_cnt=$1
if test $files_cnt -lt 10; then
	fmt="%d"
elif test $files_cnt -lt 100; then
	fmt="%02d"
elif test $files_cnt -lt 1000; then
	fmt="%03d"
elif test $files_cnt -lt 10000; then
	fmt="%04d"
else
	echo "Too many files - please extend this script" >&2
	exit 1
fi

fmt="%s-${fmt}.%s"

index=1
ls | grep -v "~$" | _rename "$prefix" "$forreal"
if test -z "$forreal"; then
	echo
	echo "Ran in dry-mode.   Nothing done.   Run with 'real' as last parameter"
	echo "to actually rename files."
	echo
fi
exit 0
